baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Purgeme's Blogs"
theme = 'PaperMod'

[params]
defaultTheme = 'auto'
disableThemeToggle = true

[params.homeInfoParams]
Title = 'Heya'
Content = 'Welcome to my blog'


[[params.socialIcons]]# optional
name = "github"
url = "https://github.com/purgeme"
[[params.socialIcons]]# optional
name = "CV"
url = "https://purgeme.github.io"
